--user endpoints collection
MERGE INTO tbl_endpoints_list (list_id, list_title, fk_list_owner, list_created_ts) KEY (list_id) VALUES (1, 'Localhost - Users', 1, CURRENT_TIMESTAMP);
MERGE INTO tbl_endpoints_list (list_id, list_title, fk_list_owner, list_created_ts) KEY (list_id) VALUES (2, 'Localhost - Endpoints', 1, CURRENT_TIMESTAMP);

-- collection endpoints
merge into tbl_endpoint_item (endp_id, endp_name, endp_descr, endp_method, endp_url, endp_path, path_params, endp_query, query_params, endp_consumes, endp_produces, endp_headers, endp_entity, endp_authorized, endp_execute, fk_parent_list, endp_created_ts) key (endp_id) values (1, 'template', 'testing grid endpoints', 'GET', 'http://localhost:4567', '/', '', '', '', 'text/html', 'application/json', '', '', '', false, 1, CURRENT_TIMESTAMP);
merge into tbl_endpoint_item (endp_id, endp_name, endp_descr, endp_method, endp_url, endp_path, path_params, endp_query, query_params, endp_consumes, endp_produces, endp_headers, endp_entity, endp_authorized, endp_execute, fk_parent_list, endp_created_ts) key (endp_id) values (2, 'GET_HOME', 'testing grid endpoints', 'GET', 'http://localhost:4567', '/', '', '', '', 'text/html', 'application/json', '', '', '', true, 1, CURRENT_TIMESTAMP);
merge into tbl_endpoint_item (endp_id, endp_name, endp_descr, endp_method, endp_url, endp_path, path_params, endp_query, query_params, endp_consumes, endp_produces, endp_headers, endp_entity, endp_authorized, endp_execute, fk_parent_list, endp_created_ts) key (endp_id) values (3, 'CHECK_LOGIN', 'testing grid endpoints', 'GET', 'http://localhost:4567', '/check', '', '', '', 'text/html', 'application/json', '', '', '', false, 1, CURRENT_TIMESTAMP);
merge into tbl_endpoint_item (endp_id, endp_name, endp_descr, endp_method, endp_url, endp_path, path_params, endp_query, query_params, endp_consumes, endp_produces, endp_headers, endp_entity, endp_authorized, endp_execute, fk_parent_list, endp_created_ts) key (endp_id) values (4, 'POST_LOGIN', 'testing grid endpoints', 'POST', 'http://localhost:4567', '/login', '', '', '', 'application/json', 'application/json', '{\"host\":\"localhost:4567\"}', 'username=admin&password=admin', '', false, 1, CURRENT_TIMESTAMP);
merge into tbl_endpoint_item (endp_id, endp_name, endp_descr, endp_method, endp_url, endp_path, path_params, endp_query, query_params, endp_consumes, endp_produces, endp_headers, endp_entity, endp_authorized, endp_execute, fk_parent_list, endp_created_ts) key (endp_id) values (5, 'GET_GAMES', 'testing grid endpoints', 'GET', 'http://localhost:4567', '/game', '', '', '', 'text/html', 'application/json', '{\"host\": \"localhost:4567\",\"X-Requested-With\": \"XMLHttpRequest\",\"Cookie\": \"JSESSIONID=t44nvwitsi131fyp97cbc2za8;Path=/\",\"xah-user-id\": \"1\"}', '', '', false, 1, CURRENT_TIMESTAMP);
merge into tbl_endpoint_item (endp_id, endp_name, endp_descr, endp_method, endp_url, endp_path, path_params, endp_query, query_params, endp_consumes, endp_produces, endp_headers, endp_entity, endp_authorized, endp_execute, fk_parent_list, endp_created_ts) key (endp_id) values (6, 'GET_GAME_BY_ID', 'testing grid endpoints', 'GET', 'http://localhost:4567', '/game/2', '', '', '', 'text/html', 'application/json', '', '', '', false, 1, CURRENT_TIMESTAMP);
merge into tbl_endpoint_item (endp_id, endp_name, endp_descr, endp_method, endp_url, endp_path, path_params, endp_query, query_params, endp_consumes, endp_produces, endp_headers, endp_entity, endp_authorized, endp_execute, fk_parent_list, endp_created_ts) key (endp_id) values (7, 'GET_ALL_GUESTS', 'testing grid endpoints', 'GET', 'http://localhost:4567', '/guests', '', '', '', 'text/html', 'application/json', '', '', '', false, 1, CURRENT_TIMESTAMP);

-- endpoint assertions
merge into tbl_endpoint_assert (assert_id, assert_type, fail_message, expected_value, actual_value, assert_execute, fk_parent_endp, assert_created_ts) key (assert_id) values (1, 'assertContains', 'expecting to find a number 20 in the text', '20', 'questions[0].question', true, 6, CURRENT_TIMESTAMP);
merge into tbl_endpoint_assert (assert_id, assert_type, fail_message, expected_value, actual_value, assert_execute, fk_parent_endp, assert_created_ts) key (assert_id) values (2, 'assertEquals', 'expecting user id value of 1', '1', 'userIdn', true, 6, CURRENT_TIMESTAMP);
